# Generated by Django 3.1.7 on 2021-05-13 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SimCardEstimator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simcard',
            name='daemi',
            field=models.IntegerField(choices=[(0, 'خیر'), (1, 'خیر')]),
        ),
        migrations.AlterField(
            model_name='simcard',
            name='rond',
            field=models.IntegerField(choices=[(0, 'خیر'), (1, 'خیر')]),
        ),
        migrations.AlterField(
            model_name='simcard',
            name='stock',
            field=models.IntegerField(choices=[(0, 'خیر'), (1, 'خیر')]),
        ),
    ]
