# Generated by Django 3.1.7 on 2021-05-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_userhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhistory',
            name='date',
            field=models.CharField(max_length=40),
        ),
    ]
