# Generated by Django 3.1.7 on 2021-05-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_usertransactions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.CharField(default='06/03/1400', max_length=50)),
            ],
        ),
    ]
