# Generated by Django 3.2 on 2021-04-22 09:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('mileage', models.IntegerField()),
                ('year', models.IntegerField()),
                ('body_status', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=-1)),
                ('link', models.URLField(blank=True)),
                ('slug', models.SlugField(blank=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
