# Generated by Django 3.1.7 on 2021-04-24 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarEstimator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
