# Generated by Django 3.2 on 2021-04-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True)),
                ('area', models.IntegerField()),
                ('room', models.IntegerField()),
                ('year', models.IntegerField()),
                ('price', models.IntegerField(default=-1)),
                ('location', models.TextField(max_length=400)),
            ],
        ),
    ]
