# Generated by Django 3.2 on 2021-04-11 15:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HouseEstimator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='house',
            name='neighbourhood',
            field=models.TextField(default=django.utils.timezone.now, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
