# Generated by Django 3.2 on 2021-04-11 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HouseEstimator', '0002_auto_20210411_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
