# Generated by Django 3.2 on 2021-04-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HouseEstimator', '0003_alter_house_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='link',
            field=models.URLField(unique=True),
        ),
    ]
