# Generated by Django 3.2 on 2021-04-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HouseEstimator', '0005_house_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='link',
            field=models.URLField(default=None, unique=True),
        ),
    ]
