# Generated by Django 3.2 on 2021-04-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HouseEstimator', '0008_alter_house_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='link',
            field=models.URLField(unique=True),
        ),
    ]
