# Generated by Django 3.2 on 2021-04-14 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HouseEstimator', '0011_alter_house_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
